sudo: required
dist: trusty
language: node_js
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - '8'

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  matrix:
    - CI_ACTION="npm run test:firefox -- --single-run"
    - CI_ACTION="npm run test:chrome -- --single-run"
    - CI_ACTION="npm run lint"
    - CI_ACTION="npm run dist"

branches:
  only:
    - travis

cache:
  directories:
    - node_modules
